import React from "react";
import NavBar from "../NavBar/NavBar";
import {useParams} from "react-router-dom";
import CommentList from "../comments/CommentList";
import AnswerList from "../answers/AnswerList";

const QuestionDetails = () => {

    const { questionId } = useParams();

    return (<div>
        <div className="container">
            <NavBar/>
            <div className="row">
                <div className="col">
                    <div className="container">
                        <div>
                            <h1>Question {questionId} </h1>
                            <p>How can I define a route in my routes.jsx file to capture the __firebase_request_key parameter value from a URL generated by Twitter's single sign on process after the redirect from their servers?</p>
                            <pre>http://localhost:8000/#/signin?_k=v9ifuf&__firebase_request_key=blablabla</pre>
                            <p>I tried with the following routes configuration, but the :redirectParam is not catching the mentioned param:</p>
                        </div>
                        <CommentList questionId={questionId} />
                        <AnswerList questionId={questionId} />
                    </div>
                </div>
            </div>
        </div>
    </div>  );
}
export default QuestionDetails